name: Tsetlini clang sanitizer

on:
  push:
    branches:
      - 'main'
      - 'GH[1-9]+[0-9]*-*'

jobs:
  build-and-run-sanitized-code:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    env:
      CXX: clang++-11
      CXX_FLAGS: -Wall -Werror -march=native -mno-avx512f -fsanitize=address -fsanitize=undefined
    steps:
    - uses: actions/checkout@v2
    - name: Install CMake
      run: sudo apt-get install -y cmake
    - name: Install compiler
      run: sudo apt-get install -y ${CXX}
    - name: Configure
      working-directory: .build
      run: |
        cmake -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_ENABLE_GTEST_TESTS=OFF -DCMAKE_CXX_FLAGS="${CXX_FLAGS}" ..
    - name: Build
      working-directory: .build
      run: |
        cmake --build .
    - name: Run tests
      working-directory: .build/lib
      run: ctest
    - name: Run 'Noisy XOR' example
      working-directory: .build/lib/examples/noisy-xor
      run: |
        curl https://raw.githubusercontent.com/cair/TsetlinMachineCython/79f0be5c9b259d2364b4ec86d46bb6f9fd4ce787/NoisyXORTrainingData.txt -o NoisyXORTrainingData.txt
        curl https://raw.githubusercontent.com/cair/TsetlinMachineCython/79f0be5c9b259d2364b4ec86d46bb6f9fd4ce787/NoisyXORTestData.txt -o NoisyXORTestData.txt
        ./noisy-xor
